version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    environment:
      - SERVER_TYPE=gunicorn
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    user: "0"

  proxy:
    build:
      context: ./proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/vol/static:ro
      - media_volume:/vol/media:ro
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
