version: '3.9'

services:
  web:
    build: .
    working_dir: /app
    command: sh -c "/scripts/entrypoint.sh"
    volumes:
      - .:/app
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  postgres_data:
  static_volume:
  media_volume:
